version: '3'
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
 
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: backend_api
    volumes:
      - ./backend:/app
    ports: 
      - 8080:8080