server:
  servlet:
    context-path: /api
  error:
    include-message: always

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/creaming
    username: sa
    password:
    driver-class-name: org.h2.Driver

my-app:
  server-url: https://j4b106.p.ssafy.io
