server:
  servlet:
    context-path: /api
  error:
    include-message: always

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k4b204.p.ssafy.io/creaming?useUnicode=true&charaterEncoding=utf-8
    username: root
    password: creaming2021^^

my-app:
  server-url: https://k4b204.p.ssafy.io
